### ISSUE TITLE
Ensure Docker build on the one Dockerfile works in the dir it is resident in

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure-archived-2024#214] opened 2023-05-02 02:04 UTC
**Describe the solution you'd like**
As per the title. More information to come.

**Comment by Belchy06** [comment] 2023-07-27 05:37
Going to close this as it's a duplicate of https://github.com/EpicGames/PixelStreamingInfrastructure/issues/213 which will be addressed soon.

**Closed as not planned by Belchy06** 2023-07-27 05:37 UTC
Labels: enhancement
