### ISSUE TITLE
[BUG] - Mouse Wrong Location with RenderOffScreen arg

### ISSUE THREAD

**Issue by zuyi53** [EpicGames/PixelStreamingInfrastructure-archived-2024#280] opened 2023-06-26 09:06 UTC
**UE Version: **
UE 5.4

**Frontend Version: **
UE5.3-0.3.0

**Problem component**
Signalling Server, Frontend, Pixel Streaming C++ plugin

**Description**
I run the game with RenderOffscreen arg,  the mouse will not interacthe widget inside the game.  

**Steps to Reproduce:**
1. Create a Shortcut with -RenderOffScreen 
2. Start the game with the ShortCut
3. Open Browser and enter the ipaddress, click start .
4. The mouse will not interact with widget button.

**Expected behavior**
1. mouse shoud interact with widget button

**Screenshots**

**Platform (please complete the following information):**
 - OS:  Windows 11
 - Mircosoft edge 114.0.1823.58 

**Additional context**
if  i sisable the "render off screen" arg will work.   I think the my mouse location doest match the virutal mouse location.

**Comment by Belchy06** [comment] 2023-07-18 07:54
Heya @zuyi53,

Thanks for reporting this issue.

The issue is actually a problem with the Unreal Engine itself, introduced in this [commit](https://github.com/EpicGames/UnrealEngine/commit/7591296349c1f9cc95177a71bdd0cb2ed34e2d69). As it's an issue with the engine itself, I'm going to close this issue and track it internally.

Luckily, there is a workaround which is to launch your application with `-NullApplicationWorkArea=ResXxResY` and match the dimensions to whatever you would specify for your resolution. Eg If you're launching your application with `-res=1920x1080`, you'd add `-NullApplicationWorkArea=1920x1080`.

Cheers

**Closed as not planned** 2023-07-18 09:42 UTC
Labels: bug
