### ISSUE TITLE
Faild to read DnsConfig

### ISSUE THREAD

**Issue by Zydiii** [EpicGames/PixelStreamingInfrastructure-archived-2024#140] opened 2023-03-07 09:49 UTC
![image](https://user-images.githubusercontent.com/37077660/223383073-918bceff-03a2-432e-a04b-b2ebcfb06f6c.png)

Hi, I'm currently working on Pixel Streaming to run my exe on a **non-networked** pc, but I got the message `Faild to read DnsConfig` so my exe can't connet to the signalling server. 
I didn't find any file named `dns_config_service_win.cc` in my computer so I guess Unreal has build it into a lib file or other else. 
Is there anyway to support my exe connet to the signalling server running on a non-networked pc with no Wifi or network cable connected? Thanks!

**Comment by jimcccc** [comment] 2023-04-27 01:19
Ok

**Comment by lukehb** [comment] 2023-06-06 05:49
We cannot reproduce this issue. We will need more instructions to attempt a reproduction here. Closing. Feel free to reopen with reproduction steps.

**Closed as completed by lukehb** 2023-06-06 05:49 UTC
Labels: help wanted
